### ISSUE TITLE
Default mailgun_headers option

### ISSUE THREAD

**Issue by sgringwe** [jorgemanrubia/mailgun_rails#12]
I am loving this gem and the configurability of it. In particular I like how you can set mailgun_headers: "email.mailgun_headers = {foo: 'bar'}".

Going a step further, I'd like to default to mailgun_headers having testmode enabled. Only in production I want to override that to actually send emails for real. Is there a way to set config.default_mailgun_headers so that it defaults to being in test mode?

Thanks again for the great gem and let me know if there's anything I can do to help (I could maybe submit a PR if needed).

**Comment by catmando** [comment]
I assume this is issue is still open, and there is no way to set default to railgun test mode in the config file?

**Comment by somazx** [comment]
I was able to enable the testmode mailgun_option globally by setting it in application mailer:

staging environment config
```
Rails.application.configure do
  config.x.action_mailer.mailgun_options = { testmode: true }
end
```

ApplicationMailer
```
  after_action :set_mailgun_options

  private

  def set_mailgun_options
    mail.mailgun_options = Rails.configuration.x.action_mailer.mailgun_options
    true
  end
```
Is there any better way?

It would be awesome to have support for setting all the mailgun options, variables, etc thru config.action_mailer.mailgun_settings
