### ISSUE TITLE
Commas in FROM: cause "undefined method `formatted' for Mail::UnstructuredField"

### ISSUE THREAD

**Issue by MaffooClock** [jorgemanrubia/mailgun_rails#48]
After nearly an hour of hair-pulling, I've discovered that if the `from:` display name contains a comma, Mailgun throws an exception `NoMethodError (undefined method 'formatted' for #<Mail::UnstructuredField:0x007fba8303c8f8>)`.

Examples:

    Acme Manufacturing, Inc. <noreply@acmemfg.com> # <-- Throws Exception
    Acme Manufacturing Inc. <noreply@acmemfg.com>  # <-- OK

**Comment by MaffooClock** [comment]
Actually, I forgot that a comma is a delimiter for multiple addresses, so I'll have to figure out a way to escape it.

**Comment by MaffooClock** [comment]
Heh, more than a year later, and I found myself in this pitfall again!

Although not specific to this project, here's a tip: `%Q["#{addressee_name}" <#{email_address}>]`

**Comment by dkam** [comment]
I just came across this too.

**Comment by kalinchuk** [comment]
This seems to happen whenever the `from:` and `to:` fields are not formatted correctly (extra commas and periods seem to be the common ones)
