### ISSUE TITLE
Would you be willing to publish a new version of this to rubygems?

### ISSUE THREAD

**Issue by lkemmerer** [jorgemanrubia/mailgun_rails#52]
The recent addition of the mailgun message id in the mail object was really useful for me to track/store message replies.  Unfortunately, my production server isn't set up to retrieve gems from github.  Would you be able to publish a minor version update to rubygems?

Thank you!

**Comment by jorgemanrubia** [comment]
Done! Version 0.8.0 released. 

Thanks for the heads up.

**Comment by lkemmerer** [comment]
That was amazingly quick.  Thank you again!
