### ISSUE TITLE
Conflicts with the official mailgun_ruby gem

### ISSUE THREAD

**Issue by hampei** [jorgemanrubia/mailgun_rails#59]
Since you are both declaring a Mailgun::Client class I can't use both gems at the same time. 
I really like the way this gem uses ActionMailer for sending api email, but mailgun_ruby is nice for other api access, which isn't supported by this gem. 

Any chance you're willing to move to MailgunRails or Mailgun::Rails module?

**Comment by SirNerdBear** [comment]
I ran into this problem too, on a recent project. I created a pull request that fixes the namespace conflict.

#60

**Comment by jorgemanrubia** [comment]
Hi,

Sorry for the delay here. Is anyone interested in getting admin permissions on this repo/gem? I am not using this gem anymore and would love to find other maintainer for it.

Regards

**Comment by hampei** [comment]
Hi,

2 weeks ago I would probably have said yes, but since then I've had so many issues with mailgun, that I'm not sure I'll be using it for very long.

**Comment by onemanstartup** [comment]
@hampei could you share with us what are the issues with mailgun?

**Comment by hampei** [comment]
Emails getting send from ip's registered on mayor blacklists for days, requiring us to ask them to switch. Emails that are said to be delivered but haven't shown up in inboxes/spamboxes even when on fairly ok ip's. Getting frequent vague 400 errors when sending emails.

**Comment by onemanstartup** [comment]
@hampei bummer, i don't those problems yet. Thanks for telling this.

**Comment by zbcjackson** [comment]
@jorgemanrubia I can contribute to maintain this repo, since I am now using this gem to send emails via mailgun

**Comment by jorgemanrubia** [comment]
Thank you so much for offering to help @zbcjackson. I have added you as a collaborator. You have push permissions now. I am not really using the gem or mailgun anymore, so I really appreciate the help.

**Comment by zzet** [comment]
Fixed by https://github.com/jorgemanrubia/mailgun_rails/pull/68
